apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169758959
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169758959
    app.kubernetes.io/part-of: test-app-169758959
  name: java-quarkus-169758959
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169758959
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169758959
    spec:
      containers:
      - image: quay.io/hacdev/aedli7qw-tenant/test-app-169758959/java-quarkus-169758959@sha256:31d7fa81a08a2804bc098f71954b42963b8654da71ee6484ceeffae6a3af078c
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
